/**
 * Database client — opens `iron.db`, runs the generated Drizzle migrations and
 * seeds the catalogue on first launch. See docs/02-ARCHITECTURE.md.
 *
 * Everything downstream of this file reads and writes SYNCHRONOUSLY (docs/09 §1,
 * §3): repositories call `db.…get()/.all()/.run()` straight in render and in tap
 * handlers, so a logged set is committed before the handler returns. The only
 * asynchronous thing here is `initDatabase`, which the root layout awaits once at
 * start, before any screen mounts.
 */
import { drizzle, type ExpoSQLiteDatabase } from 'drizzle-orm/expo-sqlite';
import { migrate } from 'drizzle-orm/expo-sqlite/migrator';
import * as Crypto from 'expo-crypto';
import { File } from 'expo-file-system';
import * as SecureStore from 'expo-secure-store';
import { deleteDatabaseSync, openDatabaseSync, type SQLiteDatabase, type SQLiteOpenOptions } from 'expo-sqlite';

import { displayPhrase, encodePhrase, normalisePhrase } from '@/lib/recoveryPhrase';

// Generated by `npm run db:generate`. The .sql files are bundled by Metro —
// see `sourceExts` in metro.config.js. Never edit a migration that has shipped.
import migrations from '../../drizzle/migrations';
import * as schema from './schema';
import { seedIfNeeded } from './seed';

export const DB_NAME = 'iron.db';

/* ============================ encryption ================================= */

/**
 * SQLCipher is compiled in (app.json -> expo-sqlite `useSQLCipher`), but a database
 * is only actually encrypted if a key is set as the FIRST statement on the
 * connection. Without one the file was plain SQLite: anything that could copy it
 * off the device could read every set, weight and meal in it.
 *
 * The key comes from the recovery phrase (`src/lib/recoveryPhrase.ts`), which is the
 * root secret: 120 random bits per install, held by the OS keystore through
 * expo-secure-store and shown in Settings so it can be written down. SQLCipher runs
 * its own PBKDF2 over the phrase, so there is no key derivation in JS.
 *
 * It has to be legible for one reason: a backup you cannot decrypt on a new phone is
 * not a backup. An earlier build generated 32 unrecoverable random bytes instead;
 * `rekeyFromLegacy` moves those installs across.
 *
 * Encrypting an install that already has a plaintext `iron.db` is the dangerous
 * part, so the order below is deliberate:
 *   1. the key is stored BEFORE any data moves, so a migration interrupted by a
 *      force-quit can be finished on the next launch instead of stranding the data;
 *   2. the encrypted copy is built beside the original and read back;
 *   3. only then is the plaintext file deleted.
 * Any failure leaves the plaintext database exactly where it was and the app opens
 * it unencrypted, because a readable database beats an empty one.
 */
const PHRASE_ID = 'iron.db.phrase';
/** Pre-phrase installs: 32 random bytes as hex, which no one could ever write down. */
const LEGACY_KEY_ID = 'iron.db.key';
const MIGRATING_NAME = 'iron-migrating.db';

const fileAt = (path: string) => new File(path.startsWith('file://') ? path : `file://${path}`);

/**
 * The recovery phrase, which is the root secret — see `src/lib/recoveryPhrase.ts`.
 * Null only if the keystore is unavailable, in which case the app runs unencrypted.
 */
function databasePhrase(): string | null {
  try {
    const existing = SecureStore.getItem(PHRASE_ID);
    if (existing) return existing;
    const phrase = normalisePhrase(encodePhrase(Crypto.getRandomBytes(15)));
    SecureStore.setItem(PHRASE_ID, phrase);
    return phrase;
  } catch {
    return null;
  }
}

/**
 * Opens a database FILE by absolute path with this install's key, on its own
 * connection — for reading a downloaded backup without disturbing the live one.
 * A file encrypted with a different phrase simply fails to read, which is the
 * check that a backup belongs to this install.
 */
export function openKeyedDatabaseFile(path: string): SQLiteDatabase {
  const key = databasePhrase();
  if (key === null) throw new Error('This device has no keystore, so backups cannot be read.');
  const cut = path.lastIndexOf('/');
  return openKeyed(path.slice(cut + 1), key, { useNewConnection: true }, path.slice(0, cut));
}

/** The phrase as shown to the user. Read from Settings, never regenerated. */
export function recoveryPhrase(): string | null {
  try {
    const stored = SecureStore.getItem(PHRASE_ID);
    return stored ? displayPhrase(stored) : null;
  } catch {
    return null;
  }
}

/** `PRAGMA key` has to be the first statement the connection ever runs. */
function openKeyed(name: string, key: string, options: SQLiteOpenOptions = {}, directory?: string): SQLiteDatabase {
  const handle = openDatabaseSync(name, options, directory);
  handle.execSync(`PRAGMA key = '${key}';`);
  return handle;
}

/**
 * Moves an install off the unrecoverable random key onto the phrase. `PRAGMA rekey`
 * re-encrypts in place — no copy, no export, nothing to interrupt halfway. Idempotent:
 * if the raw key no longer opens the file the rekey already happened, so the legacy
 * entry is simply dropped.
 */
function rekeyFromLegacy(phrase: string): void {
  let legacy: string | null = null;
  try {
    legacy = SecureStore.getItem(LEGACY_KEY_ID);
  } catch {
    return;
  }
  if (!legacy) return;

  let handle: SQLiteDatabase | null = null;
  try {
    handle = openDatabaseSync(DB_NAME, { useNewConnection: true });
    handle.execSync(`PRAGMA key = "x'${legacy}'";`);
    userVersion(handle); // throws unless the raw key really does open it
    handle.execSync(`PRAGMA rekey = '${phrase}';`);
  } catch {
    /* already rekeyed, or never encrypted with it — either way the entry is dead */
  } finally {
    handle?.closeSync();
  }
  // Fire and forget: only an async delete exists, and the rekey above is idempotent,
  // so a failed cleanup just means the next launch tries the dead key once more.
  void SecureStore.deleteItemAsync(LEGACY_KEY_ID).catch(() => undefined);
}

function userVersion(handle: SQLiteDatabase): number {
  return Number(handle.getFirstSync<{ user_version: number }>('PRAGMA user_version;')?.user_version ?? 0);
}

/**
 * Copies everything from an open database into a new encrypted file at `destPath`.
 * `sqlcipher_export` carries the schema and rows but not `user_version`, so that is
 * set across by hand — the Drizzle migrator's own bookkeeping is a table and rides along.
 */
function exportEncrypted(from: SQLiteDatabase, destPath: string, key: string): void {
  const version = userVersion(from);
  from.execSync(`ATTACH DATABASE '${destPath}' AS dest KEY '${key}';`);
  try {
    from.execSync(`SELECT sqlcipher_export('dest');`);
    from.execSync(`PRAGMA dest.user_version = ${version};`);
  } finally {
    from.execSync('DETACH DATABASE dest;');
  }
}

/** Tables in a keyed database, or -1 if the key does not open it. The migration's receipt. */
function keyedTableCount(name: string, key: string): number {
  let handle: SQLiteDatabase | null = null;
  try {
    handle = openKeyed(name, key, { useNewConnection: true });
    return Number(handle.getFirstSync<{ n: number }>(`SELECT count(*) AS n FROM sqlite_master WHERE type = 'table';`)?.n ?? 0);
  } catch {
    return -1;
  } finally {
    handle?.closeSync();
  }
}

function discard(path: string): void {
  try {
    fileAt(path).delete();
  } catch {
    /* already gone */
  }
}

/** deleteDatabaseSync throws when there is no such file; nothing here is worth a boot crash. */
function dropDatabase(name: string): void {
  try {
    deleteDatabaseSync(name);
  } catch {
    /* already gone */
  }
}

/** Plaintext -> encrypted, via a temp file, keeping the original until the copy reads back. */
function encryptPlaintext(key: string, mainPath: string, tempPath: string): boolean {
  try {
    const plain = openDatabaseSync(DB_NAME, { useNewConnection: true });
    try {
      exportEncrypted(plain, tempPath, key);
    } finally {
      plain.closeSync();
    }
    if (keyedTableCount(MIGRATING_NAME, key) <= 0) {
      discard(tempPath);
      return false;
    }

    // The copy reads back under the key, so the original can go. deleteDatabaseSync
    // takes the -wal and -shm sidecars with it; a stale one would break the new file.
    deleteDatabaseSync(DB_NAME);
    const from = openKeyed(MIGRATING_NAME, key, { useNewConnection: true });
    try {
      exportEncrypted(from, mainPath, key);
    } finally {
      from.closeSync();
    }
    if (keyedTableCount(DB_NAME, key) <= 0) return false; // temp survives, resumed next launch
    deleteDatabaseSync(MIGRATING_NAME);
    return true;
  } catch {
    return false;
  }
}

/**
 * Opens `iron.db`, encrypting it on the way if this install predates encryption.
 * Returns the handle the whole app then uses.
 */
function openMainDatabase(): SQLiteDatabase {
  const key = databasePhrase();
  if (key === null) return openDatabaseSync(DB_NAME, { enableChangeListener: true });

  // Anyone already running the random-key build moves across before anything else,
  // so their first backup is one they can actually decrypt on another phone.
  rekeyFromLegacy(key);

  // databasePath is the only reliable way to learn where expo-sqlite keeps its files.
  // Opening also CREATES an empty file when there is none, which the zero case below
  // cleans up — a stray plaintext header would stop the keyed open from working.
  const probe = openDatabaseSync(DB_NAME, { useNewConnection: true });
  const dir = probe.databasePath.slice(0, probe.databasePath.lastIndexOf('/'));
  const mainPath = `${dir}/${DB_NAME}`;
  const tempPath = `${dir}/${MIGRATING_NAME}`;
  // An encrypted file opens fine and only fails on the first read, so: -1 means it
  // already needs the key, 0 means there is nothing in it, more means plaintext data.
  let tables: number;
  try {
    tables = Number(probe.getFirstSync<{ n: number }>(`SELECT count(*) AS n FROM sqlite_master WHERE type = 'table';`)?.n ?? 0);
  } catch {
    tables = -1;
  }
  probe.closeSync();

  const halfDone = fileAt(tempPath).exists;

  if (tables > 0) {
    if (halfDone) discard(tempPath); // stale attempt; the original is still intact
    if (!encryptPlaintext(key, mainPath, tempPath)) {
      return openDatabaseSync(DB_NAME, { enableChangeListener: true });
    }
  } else if (tables === 0) {
    dropDatabase(DB_NAME); // empty, possibly only just created by the probe
    if (halfDone) {
      // Killed after the plaintext file was removed: the data is in the temp copy.
      try {
        const from = openKeyed(MIGRATING_NAME, key, { useNewConnection: true });
        try {
          exportEncrypted(from, mainPath, key);
        } finally {
          from.closeSync();
        }
        if (keyedTableCount(DB_NAME, key) > 0) dropDatabase(MIGRATING_NAME);
      } catch {
        /* try again next launch — never delete the only copy */
      }
    }
  } else if (halfDone && keyedTableCount(DB_NAME, key) > 0) {
    dropDatabase(MIGRATING_NAME); // migration finished, only its cleanup was cut short
  }

  return openKeyed(DB_NAME, key, { enableChangeListener: true });
}

/**
 * Raw handle — kept exported for PRAGMAs and for the CSV/JSON export service.
 * `enableChangeListener` is not optional: it is the mechanism `useLiveQuery`
 * (docs/09 §2) uses to re-render a screen when a write lands.
 */
export const expoDb: SQLiteDatabase = openMainDatabase();

export const db: ExpoSQLiteDatabase<typeof schema> = drizzle(expoDb, { schema });

/** Memoised so a second call (fast refresh, a remount) is a no-op, not a re-migrate. */
let initialising: Promise<void> | null = null;

/**
 * Idempotent: PRAGMAs, migrations, seed. Safe to call once at app start, and
 * safe to call again. On failure the memo is cleared so the caller can retry
 * rather than being wedged behind a rejected promise forever.
 */
export async function initDatabase(): Promise<void> {
  if (initialising === null) {
    initialising = runInit().catch((error: unknown) => {
      initialising = null;
      throw error;
    });
  }
  return initialising;
}

async function runInit(): Promise<void> {
  // WAL: a set logged mid-session commits without blocking the read that redraws
  // the list. Must be set before the first write, and it persists in the file.
  expoDb.execSync('PRAGMA journal_mode = WAL;');
  // SQLite defaults foreign keys OFF per connection. The schema's ON DELETE
  // CASCADE rules (session -> set_log, routine -> day -> slot) are dead without this.
  expoDb.execSync('PRAGMA foreign_keys = ON;');

  await migrate(db, migrations);
  seedIfNeeded();
}
