/**
 * Database client — opens `iron.db`, runs the generated Drizzle migrations and
 * seeds the catalogue on first launch. See docs/02-ARCHITECTURE.md.
 *
 * Everything downstream of this file reads and writes SYNCHRONOUSLY (docs/09 §1,
 * §3): repositories call `db.…get()/.all()/.run()` straight in render and in tap
 * handlers, so a logged set is committed before the handler returns. The only
 * asynchronous thing here is `initDatabase`, which the root layout awaits once at
 * start, before any screen mounts.
 */
import { drizzle, type ExpoSQLiteDatabase } from 'drizzle-orm/expo-sqlite';
import { migrate } from 'drizzle-orm/expo-sqlite/migrator';
import { openDatabaseSync, type SQLiteDatabase } from 'expo-sqlite';

// Generated by `npm run db:generate`. The .sql files are bundled by Metro —
// see `sourceExts` in metro.config.js. Never edit a migration that has shipped.
import migrations from '../../drizzle/migrations';
import * as schema from './schema';
import { seedIfNeeded } from './seed';

export const DB_NAME = 'iron.db';

/**
 * Raw handle — kept exported for PRAGMAs and for the CSV/JSON export service.
 * `enableChangeListener` is not optional: it is the mechanism `useLiveQuery`
 * (docs/09 §2) uses to re-render a screen when a write lands.
 */
export const expoDb: SQLiteDatabase = openDatabaseSync(DB_NAME, {
  enableChangeListener: true,
});

export const db: ExpoSQLiteDatabase<typeof schema> = drizzle(expoDb, { schema });

/** Memoised so a second call (fast refresh, a remount) is a no-op, not a re-migrate. */
let initialising: Promise<void> | null = null;

/**
 * Idempotent: PRAGMAs, migrations, seed. Safe to call once at app start, and
 * safe to call again. On failure the memo is cleared so the caller can retry
 * rather than being wedged behind a rejected promise forever.
 */
export async function initDatabase(): Promise<void> {
  if (initialising === null) {
    initialising = runInit().catch((error: unknown) => {
      initialising = null;
      throw error;
    });
  }
  return initialising;
}

async function runInit(): Promise<void> {
  // WAL: a set logged mid-session commits without blocking the read that redraws
  // the list. Must be set before the first write, and it persists in the file.
  expoDb.execSync('PRAGMA journal_mode = WAL;');
  // SQLite defaults foreign keys OFF per connection. The schema's ON DELETE
  // CASCADE rules (session -> set_log, routine -> day -> slot) are dead without this.
  expoDb.execSync('PRAGMA foreign_keys = ON;');

  await migrate(db, migrations);
  seedIfNeeded();
}
