#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Firebase for Iron"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Add Firebase to the project you already have"
warn "Do NOT create a new Firebase project."
say  "A Firebase project IS a Google Cloud project. Adding Firebase to the 'Iron'"
say  "project you already made means the OAuth client behind Drive backup is reused."
say  "A separate project creates a second client ID, and Google sign-in then fails"
say  "with an audience mismatch that reports itself as a generic sign-in error."
open_url "https://console.firebase.google.com/"
step "Click 'Create a project' — then, on the first screen, look for the option to"
step "  add Firebase to an EXISTING Google Cloud project and pick 'Iron'."
step "Google Analytics: your call. Off keeps the Data Safety form simpler."
pause "Press Enter once Firebase is enabled on the Iron project."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Register a Web app"
say "Iron uses the Firebase JS SDK, so it needs Web app config — not google-services.json."
step "Project overview -> the '</>' (Web) icon -> Add app"
step "Nickname: Iron. Do NOT tick Firebase Hosting."
step "Register the app. The config block it shows is what we need next."
note "Those values are public by design: they ship inside the APK. Firebase security"
note "rules are what actually protect the data, not the secrecy of these strings."
pause "Press Enter once you can see the firebaseConfig block."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Copy the config values"
say "From that firebaseConfig block, one at a time:"
ask EXPO_PUBLIC_FIREBASE_API_KEY "apiKey:"
ask EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN "authDomain:"
ask EXPO_PUBLIC_FIREBASE_PROJECT_ID "projectId:"
ask EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET "storageBucket:"
ask EXPO_PUBLIC_FIREBASE_SENDER_ID "messagingSenderId:"
ask EXPO_PUBLIC_FIREBASE_APP_ID "appId:"
write_env EXPO_PUBLIC_FIREBASE_API_KEY "$EXPO_PUBLIC_FIREBASE_API_KEY"
write_env EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN "$EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN"
write_env EXPO_PUBLIC_FIREBASE_PROJECT_ID "$EXPO_PUBLIC_FIREBASE_PROJECT_ID"
write_env EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET "$EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET"
write_env EXPO_PUBLIC_FIREBASE_SENDER_ID "$EXPO_PUBLIC_FIREBASE_SENDER_ID"
write_env EXPO_PUBLIC_FIREBASE_APP_ID "$EXPO_PUBLIC_FIREBASE_APP_ID"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Turn on the two sign-in methods"
open_url "https://console.firebase.google.com/project/_/authentication/providers"
step "Authentication -> Get started, if you have not already."
step "Enable 'Email/Password'. Leave passwordless/email-link off."
step "Enable 'Google'. Expand 'Web SDK configuration' and CHECK that the Web client"
step "  ID shown there matches the one already in .env. If it differs, paste the"
step "  Firebase one in below — it is the one the app must use."
ask EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID "Web client ID Firebase lists [Enter keeps the current one]:"
write_env EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID "$EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID"
warn "If that value changed, Drive backup needs the new client ID to have the Drive"
warn "API enabled — it will, since both now live in the Iron project."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Create Firestore and Storage"
say "Firestore holds one small profile document per user. Storage holds the"
say "encrypted backup blob, which nobody but the user can read."
open_url "https://console.firebase.google.com/project/_/firestore"
step "Create database -> Production mode (locked). We ship real rules, not test mode."
step "Location: asia-south1 (Mumbai) if your users are in India — it cannot be changed later."
pause "Press Enter once Firestore exists."
open_url "https://console.firebase.google.com/project/_/storage"
step "Get started -> Production mode -> same location as Firestore."
pause "Press Enter once Storage exists."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Done — what happens next"
say "Everything is in .env. Nothing here is a secret, so it is safe to share."
say ""
say "Tell Claude: 'firebase config is in .env'. It will then:"
note "  - publish these to EAS so builds can see them (the bug that hid Drive)"
note "  - deploy Firestore and Storage rules that let a user reach only their own data"
note "  - build signup, the separate unticked marketing opt-in, and account deletion"
say ""
warn "One thing only you can do: Play requires a PUBLIC WEB URL where an account can"
warn "be deleted without installing the app. GitHub Pages is enough. It is mandatory"
warn "for any app with accounts, and reviewers do check it."
finish
